POST http://localhost:3000/auth
Content-Type: application/json

{
  "username": "alex",
  "password": "pass123"
}
### login ok

> {%
client.global.set("token",response.body.token)
%}

### User login Status code:200

GET http://localhost:3000/auth
Content-Type: application/json
Authorization: Bearer {{token}}

### Authorization

DELETE http://localhost:3000/books/id
Accept: application/json
Authorization: Bearer {{token}}
### Admin delete book 200

DELETE http://localhost:3000/books/id
Accept: application/json

### bad unauthAdmin delete book


PUT http://localhost:3000/books/id
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Harry Potter",
  "pages": "20"
}
### Admin update book Status code:200

PUT http://localhost:3000/books/id
Content-Type: application/json

{
    "title": "Harry Potter",
    "pages": "20"
}
### Admin update book Status code:404 unauth

POST http://localhost:3000/books
Content-Type: application/json

{
  "author": "Chinua Achebe",
  "country": "UK",
  "pages": 209,
  "title": "The Big Brother",
  "year": 1958
}
### Administrator add auction Status code:404 UNAUTHORIZED

POST http://localhost:3000/books
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "author": "Chinua Achebe",
    "country": "UK",
    "pages": 209,
    "title": "The Big Brother",
    "year": 1958
}
### Administrator add auction Status code:201 (created)

GET http://localhost:3000/books/bids
Content-Type: application/json
Authorization: Bearer {{token}}

### get bids for user 200

GET http://localhost:3000/books/bids
Content-Type: application/json

### get bids for user 404 unauth

GET http://localhost:3000/bids
Content-Type: application/json
Authorization: Bearer {{token}}

{
   "username": "alex",
    "amount": "12"
}

### post bid

GET http://localhost:3000/bids
Content-Type: application/json

{
   "username": "alex",
    "amount": "12"
}

### bad post bid

GET http://localhost:3000/bids
Accept: application/json

### User's books you place a bid

DELETE http://localhost:3000/books/1/bids?id=3
Accept: application/json
Authorization: Bearer {{token}}

### Delete bid

DELETE http://localhost:3000/books/1/bids?id=3
Accept: application/json

### bad Delete bid

POST http://localhost:3000/books/1/bids
Content-Type: application/json

{
    "username": "Jason",
    "amount": "5"
}
### Add bid Status code:404 not authorized

POST http://localhost:3000/books/1/bids
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "username": "Jason",
    "amount": "5"
}
### Add bid Status code:201 (created)

GET http://localhost:3000/books/?year=1979
Accept: application/json

### All books with publisher Status code:200

GET http://localhost:3000/books/?year=2077
Accept: application/json

### All books with publisher Status code:404

GET http://localhost:3000/books/?author=Hans Christian Andersen
Accept: application/json

### All books author J.K. Status code:200

GET http://localhost:3000/books/?author=Alexandru
Accept: application/json

### All books author Alexandru Status code:404

GET http://localhost:3000/books/?country=Denmark
Content-Type: application/json

### All books type adventures Status code: 200

GET http://localhost:3000/books/?country=Romania
Content-Type: application/json

### All books from Romania Status code: 404

GET http://localhost:3000/books
Accept: application/json

### Retrieve all books Status code: 200

GET http://localhost:3000/books/1/bids
Accept: application/json

### Retrieve all bids for a specific book Status code:200

GET http://localhost:3000/books/100/bids
Accept: application/json

### Retrieve all bids for a specific book, book doesn't exists Status code:404

GET http://localhost:3000/books/1
Accept: application/json

### Retrieve a book Status code: 200

GET http://localhost:3000/books/10012
Accept: application/json

### Book doesn't exists Status code: 404
