POST http://localhost:3000/auth
Content-Type: application/json

{
  "username": "alex",
  "password": "pass123"
}

> {%
client.global.set("token",response.body.token)
%}

### User login Status code:200

GET http://localhost:3000/auth
Content-Type: application/json
Authorization: Bearer {{token}}

### Authorization

GET http://localhost:3000/bids
Content-Type: application/json
Authorization: Bearer {{token}}

### bids for a user

DELETE http://localhost:3000/auth
Content-Type: application/json
Authorization: Bearer {{token}}

### Logout

POST http://localhost:3000/auth
Content-Type: application/json

{
  "username": "Nick",
  "password": "pass123"
}
### User login doesn't exists Status code:401

POST http://localhost:3000/users
Content-Type: application/json

{
  "username": "alex",
  "password": "pass123"
}
### User already exists Status code:400 (created)

POST http://localhost:3000/users
Content-Type: application/json

{
  "username": "Nick",
  "password": "pistol"
}
### User register done Status code:201 (created)